name: test_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^1.4.1
  flutter_fortune_wheel: ^1.2.0
  flutter_sequence_animation: "^4.0.0-nullsafety"
  flutter_staggered_animations: "^1.0.0"
  lottie: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
